# Generated by Django 5.0.6 on 2024-07-24 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_warehouse_review_inventory_product_warehouse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehouse',
            name='Отчество владельца',
        ),
        migrations.AddField(
            model_name='warehouse',
            name='owner_surname',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Отчество владельца'),
        ),
    ]
